Ability to chain the root view
inertiajs/inertia-laravel pull request #280
Opened 2021-06-24 09:07 UTC by MarGul

Very small change and mostly for semantics.

I have a guest section of my app where I need a new root-view.

Instead of doing 
```
Inertia::setRootview('guest');

return Inertia::render('Guest/Home');
```

I can not do this instead: `return Inertia::setRootView('guest')->render('Guest/Home');`

Nothing much but I like it this way instead. What do you say?

2021-07-28 08:37 UTC, claudiodekker commented
Hey @MarGul,

Thanks for this! I do dig the idea, although the only thing I somewhat dislike is that:
- `setRootView` doesn't read that nice when chaining
- People rely on the current implementation of `setRootView`

Which makes me wonder whether we should (in addition to this change) add an 'alias' method that we could use for this? In either case, I'm definitely OK with these changes, so I'll just approve it for now as-is.

@reinink thoughts?

2021-07-28 08:37 UTC, claudiodekker approved these changes

2021-07-28 09:02 UTC, MarGul commented
@claudiodekker agree that the name `setRootView` doesn't read very well when chaining. Maybe we could add the rootview as a third param in `render`? Like `Inertia::render('Gest\Home', ['param' => 'test'], 'guest')`? Basically "just" make the render method call `setRootView` before returning the response? Maybe `render` is doing too much then but just an idea.

2021-07-28 10:48 UTC, reinink commented
Hmm, my primary concern with this change is that `Inertia::setRootView()` currently affects things globally for Inertia. It will change the root view for all subsequent Inertia responses. I worry that chaining like this makes it feel like a local change only. For example:

```php
$authResponse = Inertia::render('Auth/Home');
$guestResponse = Inertia::setRootView('guest')->render('Guest/Home');

if (Auth::user()) {
    return $authResponse; // will use "guest" root view
}
```

Obviously this is silly code, but it illustrates that someone could inadvertently change the root view globally without realizing it.

The better way to solve this is not in the `ResponseFactory`, but rather in the `Response` class. That way the root view change would just be applied to that response, and not changed globally. It also solves the naming issue.

```php
return Inertia::render('Guest/Home')->rootView('guest');
```

Feel free to update this PR accordingly. 👍

2021-07-28 11:05 UTC, reinink requested changes
Add `rootView()` to the `Response` class instead, as per [this comment](https://github.com/inertiajs/inertia-laravel/pull/280#issuecomment-888211336).

2021-07-30 08:24 UTC, MarGul commented
This was a way better solution @reinink ! I have pushed the code now and tried it out. Works perfect for me now because I have one rootView for my `guest` area and one rootView for my `admin` area that I easily can handle now. Thanks!

2021-07-30 10:32 UTC, merged

2021-07-30 10:33 UTC, reinink commented
@MarGul Awesome, thanks!

2021-07-30 10:34 UTC, reinink commented
This has been released: https://github.com/inertiajs/inertia-laravel/releases/tag/v0.4.4

(I still need to write the release notes)

2021-07-30 13:04 UTC, dillingham commented
@reinink Maybe for 1.0 it could be called `layout()` throughout?

Nice feature for sure 🙌